//Q1 
//  console.log ("Q1");
//  for (let index = 0; index <=20 ; index++) {
//         if(index % 2 ===1 ){
//             console.log(index);
//         }
//  }


//  Q2 :-
// for (var i = 100 ;i >0 ; i--){
//     if (i%3 === 0){
//         console.log(i);
//     }
// }


// Q3
// console.log("Q3")
// for (let i = 4; i >= -3.5; i-=1.5 ) {
//     console.log (i);
// }


// Q4:-
    // var sum = 0 ;
    // for (var i = 1 ; i<101 ; i++){
    //     sum +=i;
    // }
    // console.log(sum);


// Q5
    var x = 1 ;
    for (var i = 1 ; i <= 12 ; i++ ) {
         x = x * i ;
    }
        console.log(x);

